### ISSUE TITLE
send C-c to sbt

### ISSUE THREAD

**Issue by fommil** [hvesalai/sbt-mode#24]
It is possible to kill forked processes from the CLI with C-c

http://stackoverflow.com/questions/5137460/sbt-stop-run-without-exiting

but sbt-mode doesn't seem to pass through the C-c

I did something like this in `maker-mode` https://github.com/fommil/maker-mode/blob/master/maker-mode.el#L203 and it would be reasonably easy to add the same support to sbt-mode (note there is a control sequence in the `maker-kill` function)

**Comment by hvesalai** [comment]
https://github.com/hvesalai/sbt-mode/blob/master/sbt-mode.el#L266

**Comment by fommil** [comment]
@hvesalai I don't get what you mean. Are you saying that the `C-c l` binding would conflict with `C-c`?

**Comment by hvesalai** [comment]
Hmm... actually did you already try using the `comint-interrupt-subjob` command? 

When you press `C-c` in Bash, it will send SIGINT to the subprocess. The command above sends it from emacs. It is bound by default to `C-c C-c` in sbt-mode (see `C-h f sbt-mode` for list of all key bindings)

**Comment by fommil** [comment]
oooh, I didn't know about that! I'll try that out and report back if it doesn't work. Thanks!
