### ISSUE TITLE
don't open a new window if a window is already open (in another frame)

### ISSUE THREAD

**Issue by fommil** [hvesalai/sbt-mode#25]
Currently the logic for `sbt-command` is quite smart about opening up windows in the current frame, but if an sbt buffer is already open in another frame, then a new window is always created in the current frame.

It would be good if the detection was along the lines of "if there is an sbt window open in any buffer, then don't do anything"

**Comment by epost** [comment]
Is there some global setting in emacs to *prevent* it from being smart about things like detecting open buffers in other frames? For example, if I do ``sbt-command`` in the current frame, I typically want it to open the buffer in the current frame, regardless of whether the file is already open in another frame.

**Comment by fommil** [comment]
I have proposed a much simpler solution: a boolean flag (`t` by default) to display the buffer when running a command.
