### ISSUE TITLE
Exiting a console session

### ISSUE THREAD

**Issue by nloyola** [hvesalai/sbt-mode#30]
When I exit a console session using `:quit` or Ctrl-D and then use `M-x sbt-run-previous-command` I get the following output in my SBT window:

```
:quit
[error] Expected symbol
[error] Not a valid command: :
[error] :quit
[error]  ^
```

Is there a way to avoid this being generated?

The only way I've been able to do it so far is to close my SBT window and start a new session.

Thanks

**Comment by hvesalai** [comment]
I am unable to reproduce this.

`M-x sbt-run-previous-command` is meant to runs what ever command was last executed with `M-x sbt-command`. The default (i.e. what is run if `sbt-command` was never used in the session) is set to the `sbt:default-command` configurable variable.

Are you saying you never used `sbt-command :quit`? If so, can you give me a more detailed transcription of your whole session. I.e. everything you do from the start of your emacs session until you execute `M-x sbt-run-previous-command`.

**Comment by nloyola** [comment]
Hi,

I've created a new Emacs configuration where I only load the `sbt-mode` package. I'm using this project to compile in: https://github.com/nloyola/play-angular-require-seed. Here are the steps I take to reproduce this output:

1. Start Emacs.
1. Open a scala file (`app/Global.scala`) and I add a space at the end of one of the lines.
1. I run `M-x sbt-run-previous-command` which asks me if I want to save then file.
1. I press the Y key, and then an SBT buffer is opened and the `test:compile` command runs.
1. In the SBT buffer I then open a Scala console using the `console` command.
1. I then switch back to my scala file and add a space at the end of one of the lines (2nd time).
1. I run `M-x sbt-run-previous-command` which asks me if I want to save then file.
1. I press the Y key, and `test:compile` command runs.
1. I then switch back to my scala file and add a space at the end of one of the lines (3rd time).
1. I run `M-x sbt-run-previous-command` which asks me if I want to save then file.
1. I press the Y key, and then in the SBT buffer I see:
    ```
    [error] Expected symbol
    [error] Not a valid command: :
    [error] :quit
    [error]  ^
    ```

    Followed by the compile output.

This error output is slightly different than the one I was getting with my Emacs configuration.

Thanks for looking into this.

**Comment by hvesalai** [comment]
Hi, I still couldn't reproduce this.

Can you give me:
- OS name and version
- emacs version
- sbt version
- sbt-mode version

Can you also give me the value of `sbt:previous-command` variable in both the scala and the sbt buffer just before steps 3, 7, and 10. (Use `C-h v sbt:previous-command` to view it)

**Comment by nloyola** [comment]
I'm using the following:

* Ubuntu 15.04
* Emacs 24.5.1
* sbt 0.13.8
* sbt-mode: git commit `0e4f27c` from Tuesday June 16, 2015

The value of `sbt:previous-command` is as follows:

* before step 3: `[No match]`
* before step 7: `test:compile`
* before step 10: `test:compile`

Thanks

**Comment by hvesalai** [comment]
It must be that sbt-mode thinks it's still in console mode even though it has already exited.

The way it detects the mode is by the prompt using a set of regexes. Here's the code https://github.com/hvesalai/sbt-mode/blob/master/sbt-mode-comint.el#L102

Now for some reason in your setup the prompt isn't what sbt-mode expects and so sbt-mode doesn't switch back to normal mode.

Check out the regexp for the expected prompt of normal mode https://github.com/hvesalai/sbt-mode/blob/master/sbt-mode-comint.el#L28. The default value is that it expects `>` right at the start of the line. If this is not what you have, then you must modify (using emacs configuration subsystem or a mode-hook, etc) the value of the regex to match what you have.

**Comment by nloyola** [comment]
The Play Framework changes the prompt to look as follows:

```
[play-angular-require-seed] $ 
```

The name of the project comes from the `name` variable defined in `build.sbt`.

I set `sbt:sbt-prompt-regexp`to:

```
"^\\[[^]]+\\]\\s-*\\$\\s-*"
```

and now sbt-mode detects the mode correctly.

Thanks
