### ISSUE TITLE
sbt-command and space character

### ISSUE THREAD

**Issue by nloyola** [hvesalai/sbt-mode#31]
I'm my project I'm using scalatest and I want to test a single module. In a bash shell I can start SBT and enter the command:

```
test-only *HelloWorldSpec
```

I cannot do this in Emacs with scala-mode and the sbt-command. When I press the spacebar I get the message:

```
completion--some: Current buffer AppLoader.scala is not an sbt-buffer
```

I can however, switch to the **SBT** buffer and type the whole command.

Can this be fixed?

**Comment by epost** [comment]
:+1:

**Comment by hvesalai** [comment]
Fixed by a9b4e1ca8168941aef439a417fab2a299940e37a

**Comment by nloyola** [comment]
Thanks!

**Comment by fommil** [comment]
this seems to still be present, my workaround is to allow

```elisp
(substitute-key-definition
 ;; allows using SPACE when in the minibuffer
 'minibuffer-complete-word
 'self-insert-command
 minibuffer-local-completion-map)
```

**Comment by isomarcte** [comment]
I see that people reacted to @wedens comment with a :-1: and a :confused:. Does that mean he is incorrect?

**Comment by sideshowcoder** [comment]
This did not work for me but as I came across it to insert an actual space in the minbuffer the key sequence is `C-q <space>` which will not complete the current word as `<space>` normally would in the minibuffer. Hope this helps someone :-)
