### ISSUE TITLE
broken on Windows

### ISSUE THREAD

**Issue by fommil** [hvesalai/sbt-mode#33]
I set up a virtualbox image to test out my dev environment on Windows and I was unable to use `sbt-mode`, it just froze up emacs. `sbt` works fine from the command line. I'll see if I can zip up my virtual box image and share it with you.

**Comment by fommil** [comment]
I can now confirm that `sbt-command` does not work on Windows 7. Sending any command to the sbt buffer results in the screen being cleared and no output being shown.

Typing commands manually into the sbt buffer appear to just be ignored, with no clearing of the screen and no output shown.

In both cases, I did not see any files produced on disk as the result of the sbt operation that I wanted to perform, so I am led to believe that `sbt-mode` simply ignores input when running on Windows :cry: 

@edani don't you use Windows in your setup? Does `sbt-mode` work for you?

**Comment by fommil** [comment]
btw if I enable `debug-on-quit` and then `C-g` when running a command, this is the stacktrace:

```
Debugger entered--Lisp error: (quit)
  accept-process-output(#<process *sbt*<d:/myproject/src/>>)
  comint-send-input()
  call-interactively(comint-send-input nil nil)
  command-execute(comint-send-input)
```

**Comment by fommil** [comment]
If you could write a test for `sbt-command` I could probably wire it up to AppVeyor and get Windows testing as part of CI to save you from having to set up a windows dev environment.

**Comment by edani** [comment]
@fommil   Checking out the WinXP virtualbox you set up is still on my list. As far as sbt-mode, it works for me (Win 8). Note that I use native emacs, not Cygwin, so sbt-mode executes the `sbt.bat` that it finds on my PATH. I do notice display problems when running sbt from a cygwin console, so that may be related.

**Comment by fommil** [comment]
hmm, I'm also running native Emacs and using the `sbt.bat` in Windows 7. I guess I'll have to minimise the problem.

**Comment by fommil** [comment]
The suggestion is to disable buffering in SBThttps://groups.google.com/forum/m/#!topic/gnu.emacs.help/KPYbNh1vgzk 

This may require wrapping SBT in an `unbuffer` command that does this for us.

**Comment by fommil** [comment]
Somebody suggested disabling jline in the SBT gitter channel. I one high hopes of fixing this tomorrow without any changes needed!

**Comment by fommil** [comment]
that was it! adding `-Djline.terminal=jline.UnsupportedTerminal` to the sbt options fixed the problem.
