### ISSUE TITLE
Emacs key binding conventions not followed by using "C-c l" for "sbt-clear"

### ISSUE THREAD

**Issue by vsipuli** [hvesalai/sbt-mode#34]
In sbt-mode.el the key "C-c l" is mapped to "sbt-clear". This goes against the key binding conventions as mentioned in the [GNU Emacs Lisp Reference Manual](http://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html#Key-Binding-Conventions):

> Don’t define C-c letter as a key in Lisp programs. Sequences consisting of C-c and a letter (either upper or lower case) are reserved for users; they are the only sequences reserved for users, so do not block them.

This causes sbt-mode to override the key binding Emacs users possibly have defined globally for "C-c l", as allowed by the convention. Would it please be possible to choose another key binding that is not "C-c letter"? (I unfortunately do not have any replacement to suggest)

**Comment by hvesalai** [comment]
I'll investigate why I chose this.

**Comment by hvesalai** [comment]
The reason is that since `sbt-mode` derives from `comint-mode` and most of its keybindings start with `C-c`, I thought I was following convention. I'l change it to `C-c C-v`

**Comment by vsipuli** [comment]
Thank you!
